### PR TITLE
  media-sound/gonic: trim optional dependencies

### PR DESCRIPTION
**Pull request by sparkhom**
ffmpeg is optional, and only required for transcoding audio. Move to optfeatures.

Additionally, alsa-lib is not required to build as of [gonic v0.15.0](https://github.com/sentriz/gonic/releases/tag/v0.15.0).

### CODE REVIEW

**Comment by zpuskas** [comment]
I'll test this locally and check behaviour of gonic. As long as it does not crash I don't see a problem with this.

**Comment by zpuskas** [comment]
@sparkhom Could you please sign off on your commit? If you have a GPG key then please also sign it.

**Comment by sparkhom** [comment]
Signed off on the commit. I don't have a GPG key but lmk if you want me to make one.

**Comment by zpuskas** [comment]
NP, I can sign your commit with my key. Thanks for the contribution.

**Pull request closed without merging**
